name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: |
        npm ci
        cd client && npm ci

    - name: Run tests
      run: |
        npm test
        cd client && npm test
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27017/mapmypride_test
        JWT_SECRET: test_secret
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

    - name: Build client
      run: cd client && npm run build
      env:
        CI: false
        REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        REACT_APP_API_URL: https://api.mapmypride.com

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "mapmypride"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
      env:
        HD_MONGODB_URI: ${{ secrets.MONGODB_URI }}
        HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        HD_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
